services:
  parking-query:
    build: ./query
    volumes:
      - shared-db:/app/data
    depends_on:
      - parking-ui

  parking-ui:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - shared-db:/app/data

volumes:
  shared-db:
